### ISSUE TITLE
f32 Mul operator

### ISSUE THREAD

**Issue by rasmusgo** [Lichtso/geometric_algebra#6]
It would be convenient to implement `Mul` with `f32` as an alias for `.scale()`. This would make it possible to do

```rs
b += m.transformation(gravity) * dt;
```
instead of
```rs
b += m.transformation(gravity).scale(dt);
```

**Comment by Lichtso** [comment]
Done, see: 642d8bdbdb28ce746349b534bc460d4197df4578
